name: waltham-comments
services:
  embeddings-service:
    build:
      context: .
      dockerfile: embeddings-service/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - embeddings-models:/app/models
  meeting-downloader:
    build:
      context: .
      dockerfile: meeting-downloader/Dockerfile
    volumes:
      - meeting-videos:/app/videos
      - meeting-audio:/app/audio
  transcription-service:
    build:
      context: .
      dockerfile: transcription-service/Dockerfile
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - meeting-audio:/app/audio
      - meeting-transcriptions:/app/transcriptions
      - speaker-db:/app/data
      - transcription-models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  # web:
  #   build:
  #     context: ./waltham-comments-page
  #     dockerfile: ./waltham-comments-page/Dockerfile

volumes:
  embeddings-models:
    driver: local
    driver_opts:
      type: none
      device: "c:/workspace/waltham-comments/models"
      o: bind
  meeting-videos:
      driver: local
      driver_opts:
        type: none
        device: "c:/workspace/waltham-comments/videos"
        o: bind
  meeting-audio:
      driver: local
      driver_opts:
        type: none
        device: "c:/workspace/waltham-comments/audio"
        o: bind
  meeting-transcriptions:
      driver: local
      driver_opts:
        type: none
        device: "c:/workspace/waltham-comments/transcriptions"
        o: bind
  speaker-db:
      driver: local
      driver_opts:
        type: none
        device: "c:/workspace/waltham-comments/data"
        o: bind
  transcription-models:
      driver: local
      driver_opts:
        type: none
        device: "c:/workspace/waltham-comments/models"
        o: bind