[project]
name = "waltham-comments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "lxml[html-clean]>=6.0.2",
    "playwright>=1.57.0",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "requests-html>=0.10.0",
    "tqdm>=4.67.1",
]
