[project]
name = "waltham-comments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "fastapi>=0.128.1",
    "httpx>=0.28.0",
    "huggingface-hub[hf-xet]>=0.36.0",
    "lxml[html-clean]>=6.0.2",
    "playwright>=1.57.0",
    "psycopg[binary]>=3.2.0",
    "yoyo-migrations>=8.2.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "pytest-xdist>=3.8.0",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "requests-html>=0.10.0",
    "sentence-transformers>=5.2.2",
    "sounddevice>=0.5.3",
    "soundfile>=0.13.1",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
    "torchcodec>=0.7.0",
    "tqdm>=4.67.1",
    "whisperx>=3.7.6",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]
torchaudio = [{ index = "pytorch-cu128" }]
torchvision = [{ index = "pytorch-cu128" }]

[tool.pytest.ini_options]
addopts = "--cov=meeting-downloader --cov=transcription-service --cov=embeddings-service --cov-report=term-missing --cov-report=xml:coverage.xml -n auto"
testpaths = ["tests"]
